# Generated by Django 5.0.1 on 2024-01-11 15:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodgroup',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='bloodgroup',
            name='patient',
        ),
        migrations.AddField(
            model_name='donor',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='baseapp.bloodgroup'),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='baseapp.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='bloodgroup',
            field=models.CharField(choices=[('O positive', 'O positive'), ('O negative', 'O negative'), ('A positive', 'A positive'), ('A negative', 'A negative'), ('B positive', 'B positive'), ('B negative', 'B negative'), ('AB positive', 'AB positive'), ('AB negative', 'AB negative'), ("Don't know", "Don't know")], max_length=15),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
