# Generated by Django 5.0.1 on 2024-01-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_bloodgroup_donor_remove_bloodgroup_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bloodgroup',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='bloodgroup',
        ),
        migrations.DeleteModel(
            name='BloodGroup',
        ),
    ]
