# Generated by Django 5.0.1 on 2024-01-12 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_remove_patient_bloodgroup_remove_donor_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(default="Don't know", max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='drecommend',
            field=models.FileField(max_length=50, null=True, upload_to='drecommend/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='fundamount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='wredommend',
            field=models.FileField(max_length=50, null=True, upload_to='wrecommend'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
